### ISSUE TITLE
"Could not terminate the child" error in some cases (probably a false positive error)

### ISSUE THREAD

**Issue by eldipa** [byexamples/byexample#159]
**Describe the bug**
Sometimes `pexpect` claims that it cannot terminate the child (the interpreter) and `byexample` prints an error which it may be too severe.

This is the traceback:

```
[i:exec.cpp] Shutting down Cpp Runner
[w:exec.cpp] Shutdown of Cpp Runner failed.
[!] Something went wrong processing the file 'docs/languages/cpp.md':
Traceback (most recent call last):
  File "/home/user/env/py3env/lib/python3.7/site-packages/pexpect/pty_spawn.py", line 23, in _wrap_ptyprocess_err
    yield
  File "/home/user/env/py3env/lib/python3.7/site-packages/pexpect/pty_spawn.py", line 328, in close
    self.ptyproc.close(force=force)
  File "/home/user/env/py3env/lib/python3.7/site-packages/ptyprocess/ptyprocess.py", line 406, in close
    raise PtyProcessError('Could not terminate the child.')
ptyprocess.util.PtyProcessError: Could not terminate the child.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/proj/byexample/byexample/common.py", line 209, in human_exceptions
    yield o
  File "/home/user/proj/byexample/byexample/byexample.py", line 22, in execute_examples
    return executor.execute(examples, filename)
  File "/home/user/proj/byexample/byexample/log.py", line 267, in wrapped
    return func(*args, **kargs)
  File "/home/user/proj/byexample/byexample/executor.py", line 280, in execute
    self.reset_runners(runners)
  File "/home/user/proj/byexample/byexample/executor.py", line 239, in reset_runners
    runner.shutdown()
  File "/home/user/proj/byexample/byexample/modules/cpp.py", line 147, in shutdown
    self._shutdown_interpreter()
  File "/home/user/proj/byexample/byexample/runner.py", line 272, in _shutdown_interpreter
    self._interpreter.close()
  File "/home/user/env/py3env/lib/python3.7/site-packages/pexpect/pty_spawn.py", line 328, in close
    self.ptyproc.close(force=force)
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/user/env/py3env/lib/python3.7/site-packages/pexpect/pty_spawn.py", line 25, in _wrap_ptyprocess_err
    raise ExceptionPexpect(*e.args)
pexpect.exceptions.ExceptionPexpect: Could not terminate the child.
```

I saw this running a C++ doctest and a PHP doctest.

For the C++ case, I ran:
```shell
byexample -l cpp,shell -x-shebang="cpp:$dockercmd" --timeout 10 -vvv docs/languages/cpp.md
```

The relevant code is:

```python
    def _shutdown_interpreter(self):
        self._interpreter.sendeof()
        self._interpreter.close()
        time.sleep(0.001)
        self._interpreter.terminate(force=True)
```

Probably the interpreter terminates once we send an EOF so the next `close` triggers the error (and may be the `terminate` will too). Basically there is a race condition between `byexample` and the interpreter.

**Expected behavior**
If the interpreter was closed, the error is a false positive and should be silenced.

**byexample version**
byexample 10.0.0 (Python 3.7.3) - GNU GPLv3

**Comment by eldipa** [comment]
Not a real issue, docker (used to run `cling`) is too slow and the terminate takes time. See #129 for the enhanced log message.
