### ISSUE TITLE
get_captures fails when the got ends with a single new line

### ISSUE THREAD

**Issue by eldipa** [byexamples/byexample#51]
This shell example
```
$ echo vuln                                                                                                                    
vuln                                                                                                                           
<...>
```

makes crash ``byexample`` with the following example

```
File "a", line 1, [File Executor]
    echo vuln

AssertionError: Traceback (most recent call last):
  File "/home/user/proj/byexample/byexample/common.py", line 169, in human_exceptions
    yield
  File "/home/user/proj/byexample/byexample/byexample.py", line 25, in main
    result = executor.execute(examples, filename)
  File "/home/user/proj/byexample/byexample/executor.py", line 48, in execute
    options, runners)
  File "/home/user/proj/byexample/byexample/executor.py", line 104, in _exec
    self.concerns.finally_example(example, options)
  File "/home/user/proj/byexample/byexample/concern.py", line 245, in for_each_concern_do
    getattr(concern, method_name)(*args, **kargs)
  File "/home/user/proj/byexample/byexample/modules/clipboard.py", line 64, in finally_example
    _, captured = example.expected.get_captures(example, got, options, 0)
  File "/home/user/proj/byexample/byexample/expected.py", line 189, in get_captures
    assert captured != None
AssertionError
```

The regexp generated for the expected was:
```
\Avuln\
(?:.*?)(?<!\n)\n*\Z
```

And the got string was:
```
vuln\n
```

**Comment by eldipa** [comment]
A quick workaround would be to rewrite the example as:

```
$ echo vuln
vuln<...>
```
