### ISSUE TITLE
Capture a UnicodeError and show a nice message suggesting the use of the --encoding option.

### ISSUE THREAD

**Issue by eldipa** [byexamples/byexample#77]
**Describe the feature you'd like**
Capture ``UnicodeError`` on ``pexpect``'s expect: that exception means that the output received from the interpreter cannot be decoded (wrong encoding or it is not a valid unicode at all).

Print a nice message explaining that and showing that the encoding can be changed using ``--encoding``.

Do the same when opening a file.

**Comment by eldipa** [comment]
For example, given the file `a.md`:

```
$ cat docs/advanced/unicode.md
```

Then running

```
$ byexample -l shell --encoding ascii -vvv a.md
```

We get:

```
=> Execution of example 1 of 1 crashed.
  File "/home/user/proj/byexample/byexample/executor.py", line 334, in _exec
    example, options
  File "/home/user/proj/byexample/byexample/modules/shell.py", line 141, in run
    return PexpectMixin._run(self, example, options)
......
  File "/home/user/proj/byexample/byexample/runner.py", line 456, in _expect_prompt_or_type
    self._expect_prompt(options, countdown, prompt_re)
  File "/home/user/proj/byexample/byexample/modules/shell.py", line 202, in _expect_prompt
    self, options, countdown, prompt_re, earlier_re
  File "/home/user/proj/byexample/byexample/runner.py", line 499, in _expect_prompt
    what = self._interpreter.expect(expect, timeout=timeout)
....
    return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 321: ordinal not in range(128)
```

**Comment by eldipa** [comment]
Also, processing a unicode file we get a similar error but not coming from `pexepct`:

```
$ byexample -l shell --encoding ascii -vvv docs/advanced/unicode.md
```

We get:

```
[!] Something went wrong processing the file 'docs/advanced/unicode.md':
Traceback (most recent call last):
  File "/home/user/proj/byexample/byexample/common.py", line 209, in human_exceptions
    yield o
  File "/home/user/proj/byexample/byexample/byexample.py", line 18, in execute_examples
    examples = harvester.get_examples_from_file(filename)
  File "/home/user/proj/byexample/byexample/finder.py", line 121, in get_examples_from_file
    string = f.read()
  File "/usr/lib/python3.7/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 304: ordinal not in range(128)
```
